# This is a basic workflow to help you get started with Actions

name: Sync/gitee-sync-test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Single repo mirror
        uses: chenjunbiao/gitee-sync-test@master
        with:
          src: github/chenjunbiao
          dst: gitee/yomorun
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          white_list: "sync-test1"
          force_update: true
          debug: true
